### ISSUE TITLE
Output Samples as MCMCChains object

### ISSUE THREAD

**Issue by itsdfish** [JagsJulia/Jags.jl#18]
Hi Rob-

I would like to use Jags.jl for MCMCBenchmarks and a few other projects. I was wondering if it would be possible to output an MCMCChain object instead of the Mamba object? If it is somewhat straightforward and similar to CmdStan, I might be able to make a PR.

**Comment by goedman** [comment]
Took a quick peek. Don't think it is difficult. The samples (to be collected in a3d) are columns 2 to n_pars in the text files.

**Comment by goedman** [comment]
A problem with Jags.jl is that it includes Mamba (and thus Gadfly.jl). Maybe it's time for an update!

**Comment by itsdfish** [comment]
Thanks. I'll see if I can take care of all of those things.

**Comment by itsdfish** [comment]
Rob, I think I am close to finished. I encountered a problem in which a variable [readstring](https://github.com/JagsJulia/Jags.jl/blob/0d276eced8dfa1b14041cd972decba8882a84986/src/jagsmodel.jl#L215) is not defined. I'm guess that readstring should be replaced with str. Is that the case?

**Comment by goedman** [comment]
Hi Chris,

Maybe something like:
```
    resfile = open(file, "r")
    model2 = strip(read(resfile, String))
```

A next update of Jags.jl will drop the Mamba dependency and replace it by MCMCChains.

Rob

**Comment by itsdfish** [comment]
Oh. I understand now. open was overloaded for Mamba. I just removed readstring and it seems to work.

**Comment by goedman** [comment]
Your update seems to work great! Thanks a lot. Will update to the next major release.

**Comment by itsdfish** [comment]
No problem! I'm glad to be able to help out. I'll go ahead and close this since everything appears to be working.
