### ISSUE TITLE
Change update to n_samples

### ISSUE THREAD

**Issue by itsdfish** [JagsJulia/Jags.jl#21]
Hi Rob-

I want to propose changing the keyword argument update to n_samples so that it is clearer to the user how to set the total number of samples. Are you amenable to that?

**Comment by goedman** [comment]
That’s fine. Will try to make the change later today and push to master. Last week pushed a couple of fixes to the Readme, so next week we’ll do another release.

**Comment by itsdfish** [comment]
Sounds good. I am definitely willing to update the code. I just wanted to make sure that the change seemed sensible to you. Just let me know if you want me to change it.

**Comment by goedman** [comment]
Feel free to update it. I’m on a wedding here so don’t have a lot of time.
